### ISSUE TITLE
Issues/Code Quality Concerns

### ISSUE THREAD

**Issue by soumyadeepkun** [arijitghosh120403/Python-Scripting#1]
Here is a list of issues you might want to have a look at: 
1. https://github.com/arijitghosh120403/Python-Scripting/blob/37f7149b02db670c6a7fa1a79608067e1d20056f/FetchFiles.py#L11
Always write top-level code within 
```python3
if __name__ == "__main__":
    # Your Code Here
    # ...
```

2. https://github.com/arijitghosh120403/Python-Scripting/blob/37f7149b02db670c6a7fa1a79608067e1d20056f/FetchFiles.py#L19
When using the `next()` method, always check for `StopIteration` exception.

**Comment by Ari-Ghosh** [comment]
Changes has been done and the code is now updated
